export const popular = {
  page: 1,
  results: [
    {
      adult: false,
      gender: 1,
      id: 1245,
      known_for_department: "Acting",
      name: "Scarlett Johansson",
      original_name: "Scarlett Johansson",
      popularity: 22.7629,
      profile_path: "/8m21eocprLYuW0ywveIgThk6VM.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/ozVwXlfxqNsariipatGwa5px3Pm.jpg",
          id: 240832,
          title: "Lucy",
          original_title: "Lucy",
          overview:
            "A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic.",
          poster_path: "/kRbpUTRNm6QbLQFPFWUcNC4czEm.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 878],
          popularity: 15.6361,
          release_date: "2014-07-25",
          video: false,
          vote_average: 6.465,
          vote_count: 16388,
        },
        {
          adult: false,
          backdrop_path: "/dq18nCTTLpy9PmtzZI6Y2yAgdw5.jpg",
          id: 497698,
          title: "Black Widow",
          original_title: "Black Widow",
          overview:
            "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
          poster_path: "/7JPpIjhD2V0sKyFvhB9khUMa30d.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 12, 878],
          popularity: 11.2096,
          release_date: "2021-07-07",
          video: false,
          vote_average: 7.203,
          vote_count: 10619,
        },
        {
          adult: false,
          backdrop_path: "/9WmLfENjz1RuL0MSMZAG3qjoYWR.jpg",
          id: 315837,
          title: "Ghost in the Shell",
          original_title: "Ghost in the Shell",
          overview:
            "In the near future, Major is the first of her kind: a human saved from a terrible crash, then cyber-enhanced to be a perfect soldier devoted to stopping the world's most dangerous criminals.",
          poster_path: "/zCtL3UBgCoZzd7XTVGhvl6XY75E.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [878, 18, 28],
          popularity: 5.2039,
          release_date: "2017-03-29",
          video: false,
          vote_average: 6.095,
          vote_count: 8188,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 18277,
      known_for_department: "Acting",
      name: "Sandra Bullock",
      original_name: "Sandra Bullock",
      popularity: 22.1068,
      profile_path: "/hPHGKPAWZ8gArYXMk225rrYPoyJ.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/npFPqZeHlEPOlLEpykP6kuSsi6v.jpg",
          id: 49047,
          title: "Gravity",
          original_title: "Gravity",
          overview:
            "Dr. Ryan Stone, a brilliant medical engineer, is on her first Shuttle mission, with veteran astronaut Matt Kowalsky in command of his last flight before retiring. But on a seemingly routine spacewalk, disaster strikes. The Shuttle is destroyed, leaving Stone and Kowalsky completely alone-tethered to nothing but each other and spiraling out into the blackness of space. The deafening silence tells them they have lost any link to Earth and any chance for rescue. As fear turns to panic, every gulp of air eats away at what little oxygen is left. But the only way home may be to go further out into the terrifying expanse of space.",
          poster_path: "/kZ2nZw8D681aphje8NJi8EfbL1U.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [878, 53, 18],
          popularity: 7.4071,
          release_date: "2013-10-03",
          video: false,
          vote_average: 7.2,
          vote_count: 15656,
        },
        {
          adult: false,
          backdrop_path: "/wKrxeY6lbu7KFBsWVcMH6M8avwr.jpg",
          id: 211672,
          title: "Minions",
          original_title: "Minions",
          overview:
            "Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.",
          poster_path: "/dr02BdCNAUPVU07aOodwPYv6HCf.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [10751, 16, 12, 35],
          popularity: 5.2209,
          release_date: "2015-06-17",
          video: false,
          vote_average: 6.412,
          vote_count: 10744,
        },
        {
          adult: false,
          backdrop_path: "/pDKFL1zcHzEpmz4MJA5JJnRbJeD.jpg",
          id: 405774,
          title: "Bird Box",
          original_title: "Bird Box",
          overview:
            "Five years after an ominous unseen presence drives most of society to suicide, a survivor and her two children make a desperate bid to reach safety.",
          poster_path: "/rGfGfgL2pEPCfhIvqHXieXFn7gp.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [27, 53, 18],
          popularity: 7.1739,
          release_date: "2018-12-13",
          video: false,
          vote_average: 6.832,
          vote_count: 10147,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 976,
      known_for_department: "Acting",
      name: "Jason Statham",
      original_name: "Jason Statham",
      popularity: 18.6638,
      profile_path: "/whNwkEQYWLFJA8ij0WyOOAD5xhQ.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/32V4uHVRU2fbDsQl1dsYsZm3uba.jpg",
          id: 107,
          title: "Snatch",
          original_title: "Snatch",
          overview:
            "Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.",
          poster_path: "/8KSDI7ijEv7QVZdIyrLw5Gnhhr8.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [80, 35],
          popularity: 8.0222,
          release_date: "2000-09-01",
          video: false,
          vote_average: 7.813,
          vote_count: 9360,
        },
        {
          adult: false,
          backdrop_path: "/2uSCHUsmzb6KkQPFSxBQ7bgfJLE.jpg",
          id: 345940,
          title: "The Meg",
          original_title: "The Meg",
          overview:
            "A deep sea submersible pilot revisits his past fears in the Mariana Trench, and accidentally unleashes the seventy foot ancestor of the Great White Shark believed to be extinct.",
          poster_path: "/eyWICPcxOuTcDDDbTMOZawoOn8d.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 878, 27],
          popularity: 9.5123,
          release_date: "2018-08-09",
          video: false,
          vote_average: 6.247,
          vote_count: 7843,
        },
        {
          adult: false,
          backdrop_path: "/70AV2Xx5FQYj20labp0EGdbjI6E.jpg",
          id: 637649,
          title: "Wrath of Man",
          original_title: "Wrath of Man",
          overview:
            "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
          poster_path: "/M7SUK85sKjaStg4TKhlAVyGlz3.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 80, 53],
          popularity: 17.8552,
          release_date: "2021-04-22",
          video: false,
          vote_average: 7.61,
          vote_count: 5619,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 115440,
      known_for_department: "Acting",
      name: "Sydney Sweeney",
      original_name: "Sydney Sweeney",
      popularity: 18.0447,
      profile_path: "/uDnIdU4KGjQg7liFvb9wnALvg95.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/9KnIzPCv9XpWA0MqmwiKBZvV1Sj.jpg",
          id: 85552,
          name: "Euphoria",
          original_name: "Euphoria",
          overview:
            "A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.",
          poster_path: "/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [18],
          popularity: 82.1705,
          first_air_date: "2019-06-16",
          vote_average: 8.3,
          vote_count: 10069,
          origin_country: ["US"],
        },
        {
          adult: false,
          backdrop_path: "/j9eOeLlTGoHoM8BNUJVNyWmIvCi.jpg",
          id: 1072790,
          title: "Anyone But You",
          original_title: "Anyone But You",
          overview:
            "After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
          poster_path: "/5qHoazZiaLe7oFBok7XlUhg96f2.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [10749, 35],
          popularity: 13.1169,
          release_date: "2023-12-21",
          video: false,
          vote_average: 6.854,
          vote_count: 2610,
        },
        {
          adult: false,
          backdrop_path: "/pIFGZRCWjdQwECoXcphCCe1tl0B.jpg",
          id: 1041613,
          title: "Immaculate",
          original_title: "Immaculate",
          overview:
            "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
          poster_path: "/zyopv7D5j7cfswG0NYiA14qAdPC.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [27, 9648, 53],
          popularity: 7.5668,
          release_date: "2024-03-20",
          video: false,
          vote_average: 6.234,
          vote_count: 1439,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 1522703,
      known_for_department: "Acting",
      name: "Hande Erçel",
      original_name: "Hande Erçel",
      popularity: 17.9368,
      profile_path: "/jrUvWNqOpfDm3D0KhbuRwQOy8Nu.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/9qq8LpOoBLYq8MxiMugn0gf9qJd.jpg",
          id: 104877,
          name: "Love Is in the Air",
          original_name: "Sen Çal Kapımı",
          overview:
            "Eda, who ties all her hopes to her education, confronts Serkan Bolat, who cuts off her international education scholarship and leaves her with high school diploma. Serkan Bolat offers Eda to give her scholarship back if she pretends to be his fiance for two months. Although Eda rejects the offer of this man as she hates him, she has to accept it when the conditions change. While pretending to be engaged, Serkan and Eda begin to experience a passionate, challenging relationship that will make them forget all they know right. Because love is difficult. And that's why it's amazing.",
          poster_path: "/bE71f9A3eztjcd5JT3MmHB8MbzA.jpg",
          media_type: "tv",
          original_language: "tr",
          genre_ids: [18, 35],
          popularity: 41.0445,
          first_air_date: "2020-07-08",
          vote_average: 8.2,
          vote_count: 3070,
          origin_country: ["TR"],
        },
        {
          adult: false,
          backdrop_path: "/qAJqYEz0utqsaPsMQvgjbUatUwv.jpg",
          id: 1318917,
          title: "Chasing the Wind",
          original_title: "Rüzgara Bırak",
          overview:
            "A focused city worker and a laid-back surfer - both heirs to the same company - find they have plenty in common when they join forces in the boardroom.",
          poster_path: "/pg6sFi0pv8cPelkJGLZqmUxh24F.jpg",
          media_type: "movie",
          original_language: "tr",
          genre_ids: [10749],
          popularity: 13.4268,
          release_date: "2025-01-09",
          video: false,
          vote_average: 6.324,
          vote_count: 34,
        },
        {
          adult: false,
          backdrop_path: "/nWNH4OTbiZTxqfPOgSYI2U17aCJ.jpg",
          id: 67570,
          name: "Love Doesn't Understand Words",
          original_name: "Aşk Laftan Anlamaz",
          overview:
            "Hayat is a country girl with strict parents. She is in a love hate relationship with her boss Murat. Hayat is full of secrets that can ruin her career and relationship.",
          poster_path: "/krSdiuUrsqka7FFtaqjxEqC0bE9.jpg",
          media_type: "tv",
          original_language: "tr",
          genre_ids: [35, 18],
          popularity: 15.2053,
          first_air_date: "2016-06-15",
          vote_average: 8.4,
          vote_count: 34,
          origin_country: ["TR"],
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 28782,
      known_for_department: "Acting",
      name: "Monica Bellucci",
      original_name: "Monica Bellucci",
      popularity: 17.4981,
      profile_path: "/euhMjVgdEGFm4AzjvB1b2oSMlLU.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/xV1EfNSEg6id6juJPr1vM6p9x5X.jpg",
          id: 979,
          title: "Irreversible",
          original_title: "Irréversible",
          overview:
            "A woman’s lover and her ex-boyfriend take justice into their own hands after she becomes the victim of a rapist. Because some acts can’t be undone. Because man is an animal. Because the desire for vengeance is a natural impulse. Because most crimes remain unpunished.",
          poster_path: "/rxeDxo8FvZpLu6iplNpxdtAVnfu.jpg",
          media_type: "movie",
          original_language: "fr",
          genre_ids: [18, 53, 80],
          popularity: 8.2477,
          release_date: "2002-05-22",
          video: false,
          vote_average: 7.204,
          vote_count: 3036,
        },
        {
          adult: false,
          backdrop_path: "/3mR0TCv9mqAcEBt1Nu9SXI3VDIo.jpg",
          id: 10867,
          title: "Malena",
          original_title: "Malèna",
          overview:
            "During WWII, a teenage boy discovering himself becomes love-stricken by Malèna, a sensual woman living in a small, narrow-minded Italian town.",
          poster_path: "/doFIkrkO2gsWFju3KpIY5xUhpgJ.jpg",
          media_type: "movie",
          original_language: "it",
          genre_ids: [18],
          popularity: 9.6072,
          release_date: "2000-03-16",
          video: false,
          vote_average: 7.4,
          vote_count: 2328,
        },
        {
          adult: false,
          backdrop_path: "/8lBViysvNJBPkl6zG1LVAaW3qhj.jpg",
          id: 206647,
          title: "Spectre",
          original_title: "Spectre",
          overview:
            "A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.",
          poster_path: "/zj8ongFhtWNsVlfjOGo8pSr7PQg.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 12, 53],
          popularity: 6.1131,
          release_date: "2015-10-26",
          video: false,
          vote_average: 6.559,
          vote_count: 10746,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 974169,
      known_for_department: "Acting",
      name: "Jenna Ortega",
      original_name: "Jenna Ortega",
      popularity: 17.1692,
      profile_path: "/7oUAtVgZU0uLdUSvDHKkINt1y7Y.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
          id: 119051,
          name: "Wednesday",
          original_name: "Wednesday",
          overview:
            "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
          poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [10765, 9648, 35],
          popularity: 66.1081,
          first_air_date: "2022-11-23",
          vote_average: 8.417,
          vote_count: 9139,
          origin_country: ["US"],
        },
        {
          adult: false,
          backdrop_path: "/70Rm9ItxKuEKN8iu6rNjfwAYUCJ.jpg",
          id: 760104,
          title: "X",
          original_title: "X",
          overview:
            "In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive, elderly hosts catch them in the act, the cast find themselves fighting for their lives.",
          poster_path: "/lopZSVtXzhFY603E9OqF7O1YKsh.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [27, 53],
          popularity: 10.0409,
          release_date: "2022-03-17",
          video: false,
          vote_average: 6.744,
          vote_count: 3557,
        },
        {
          adult: false,
          backdrop_path: "/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
          id: 646385,
          title: "Scream",
          original_title: "Scream",
          overview:
            "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
          poster_path: "/1m3W6cpgwuIyjtg5nSnPx7yFkXW.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [27, 9648],
          popularity: 10.5795,
          release_date: "2022-01-12",
          video: false,
          vote_average: 6.677,
          vote_count: 3497,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 6384,
      known_for_department: "Acting",
      name: "Keanu Reeves",
      original_name: "Keanu Reeves",
      popularity: 17.1311,
      profile_path: "/8RZLOyYGsoRe9p44q3xin9QkMHv.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/icmmSD4vTTDKOq2vvdulafOGw93.jpg",
          id: 603,
          title: "The Matrix",
          original_title: "The Matrix",
          overview:
            "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
          poster_path: "/p96dm7sCMn4VYAStA6siNz30G1r.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 878],
          popularity: 28.1722,
          release_date: "1999-03-31",
          video: false,
          vote_average: 8.227,
          vote_count: 26504,
        },
        {
          adult: false,
          backdrop_path: "/7dzngS8pLkGJpyeskCFcjPO9qLF.jpg",
          id: 245891,
          title: "John Wick",
          original_title: "John Wick",
          overview:
            "Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.",
          poster_path: "/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 53],
          popularity: 13.1403,
          release_date: "2014-10-22",
          video: false,
          vote_average: 7.448,
          vote_count: 19798,
        },
        {
          adult: false,
          backdrop_path: "/r17jFHAemzcWPPtoO0UxjIX0xas.jpg",
          id: 324552,
          title: "John Wick: Chapter 2",
          original_title: "John Wick: Chapter 2",
          overview:
            "John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.",
          poster_path: "/hXWBc0ioZP3cN4zCu6SN3YHXZVO.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 53, 80],
          popularity: 17.0277,
          release_date: "2017-02-08",
          video: false,
          vote_average: 7.3,
          vote_count: 13494,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 1239253,
      known_for_department: "Acting",
      name: "Demord Dann",
      original_name: "Demord Dann",
      popularity: 16.0183,
      profile_path: "/2YldPW7ucXaU4x2f4yb7mf5fz0l.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/wTvDGO0xGMmnScqjuiDeWU7PkcB.jpg",
          id: 293863,
          title: "The Age of Adaline",
          original_title: "The Age of Adaline",
          overview:
            "After 29-year-old Adaline recovers from a nearly lethal accident, she inexplicably stops growing older. As the years stretch on and on, Adaline keeps her secret to herself  until she meets a man who changes her life.",
          poster_path: "/MbILysGhjAbnZi1Okae9wYqLMx.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [10749, 14, 18],
          popularity: 5.4309,
          release_date: "2015-04-16",
          video: false,
          vote_average: 7.48,
          vote_count: 6825,
        },
        {
          adult: false,
          backdrop_path: "/xACuC5FwpCdayrcCsJPxYzrl8BO.jpg",
          id: 97020,
          title: "RoboCop",
          original_title: "RoboCop",
          overview:
            "In RoboCop, the year is 2028 and multinational conglomerate OmniCorp is at the center of robot technology.  Overseas, their drones have been used by the military for years, but have been forbidden for law enforcement in America.  Now OmniCorp wants to bring their controversial technology to the home front, and they see a golden opportunity to do it.  When Alex Murphy – a loving husband, father and good cop doing his best to stem the tide of crime and corruption in Detroit – is critically injured, OmniCorp sees their chance to build a part-man, part-robot police officer.  OmniCorp envisions a RoboCop in every city and even more billions for their shareholders, but they never counted on one thing: there is still a man inside the machine.",
          poster_path: "/gM5ql3BKYmHG3WtZ0buKXN7xY8O.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [878, 28, 80],
          popularity: 6.6338,
          release_date: "2014-01-30",
          video: false,
          vote_average: 5.878,
          vote_count: 5593,
        },
        {
          adult: false,
          backdrop_path: "/f3cin9kOz4nOrlYEMxGFQhv4bdN.jpg",
          id: 71712,
          name: "The Good Doctor",
          original_name: "The Good Doctor",
          overview:
            "Shaun Murphy, a young surgeon with autism and savant syndrome, relocates from a quiet country life to join a prestigious hospital's surgical unit. Unable to personally connect with those around him, Shaun uses his extraordinary medical gifts to save lives and challenge the skepticism of his colleagues.",
          poster_path: "/luhKkdD80qe62fwop6sdrXK9jUT.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [18],
          popularity: 81.9142,
          first_air_date: "2017-09-25",
          vote_average: 8.477,
          vote_count: 12584,
          origin_country: ["US"],
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 1253360,
      known_for_department: "Acting",
      name: "Pedro Pascal",
      original_name: "Pedro Pascal",
      popularity: 15.879,
      profile_path: "/9VYK7oxcqhjd5LAH6ZFJ3XzOlID.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/9zcbqSxdsRMZWHYtyCd1nXPr2xq.jpg",
          id: 82856,
          name: "The Mandalorian",
          original_name: "The Mandalorian",
          overview:
            "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
          poster_path: "/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [10765, 10759, 18],
          popularity: 57.9467,
          first_air_date: "2019-11-12",
          vote_average: 8.4,
          vote_count: 10398,
          origin_country: ["US"],
        },
        {
          adult: false,
          backdrop_path: "/uQ4lG7E7mlyKsGvbASftQ6Hu2IX.jpg",
          id: 100088,
          name: "The Last of Us",
          original_name: "The Last of Us",
          overview:
            "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
          poster_path: "/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [18],
          popularity: 125.6334,
          first_air_date: "2023-01-15",
          vote_average: 8.515,
          vote_count: 6253,
          origin_country: ["US"],
        },
        {
          adult: false,
          backdrop_path: "/z7noaCJ4KtmhwHw7QcNtnMMo4Qy.jpg",
          id: 345887,
          title: "The Equalizer 2",
          original_title: "The Equalizer 2",
          overview:
            "Robert McCall, who serves an unflinching justice for the exploited and oppressed, embarks on a relentless, globe-trotting quest for vengeance when his former partner is murdered.",
          poster_path: "/cQvc9N6JiMVKqol3wcYrGshsIdZ.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 53, 80],
          popularity: 10.8086,
          release_date: "2018-07-19",
          video: false,
          vote_average: 6.776,
          vote_count: 5584,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 1892,
      known_for_department: "Acting",
      name: "Matt Damon",
      original_name: "Matt Damon",
      popularity: 15.8653,
      profile_path: "/At3JgvaNeEN4Z4ESKlhhes85Xo3.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/9pubUbDX3eKB6ZuKxbFgv4cBZrz.jpg",
          id: 286217,
          title: "The Martian",
          original_title: "The Martian",
          overview:
            "During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive.",
          poster_path: "/3ndAx3weG6KDkJIRMCi5vXX6Dyb.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [18, 12, 878],
          popularity: 9.9247,
          release_date: "2015-09-30",
          video: false,
          vote_average: 7.689,
          vote_count: 20238,
        },
        {
          adult: false,
          backdrop_path: "/oLsts7ct0NVkdYpx5rZg10MG6zh.jpg",
          id: 489,
          title: "Good Will Hunting",
          original_title: "Good Will Hunting",
          overview:
            "Headstrong yet aimless, Will Hunting has a genius-level IQ but chooses to work as a janitor at MIT. When he secretly solves highly difficult graduate-level math problems, his talents are discovered by Professor Gerald Lambeau, who decides to help the misguided youth reach his potential. When Will is arrested for attacking a police officer, Professor Lambeau makes a deal to get leniency for him if he gets court-ordered therapy. Eventually, therapist Dr. Sean Maguire helps Will confront the demons that are holding him back.",
          poster_path: "/z2FnLKpFi1HPO7BEJxdkv6hpJSU.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [18],
          popularity: 14.7083,
          release_date: "1997-12-05",
          video: false,
          vote_average: 8.158,
          vote_count: 12878,
        },
        {
          adult: false,
          backdrop_path: "/kJaRWmy1BGq3pHyE94LOTteiHer.jpg",
          id: 2501,
          title: "The Bourne Identity",
          original_title: "The Bourne Identity",
          overview:
            "Wounded to the brink of death and suffering from amnesia, Jason Bourne is rescued at sea by a fisherman. With nothing to go on but a Swiss bank account number, he starts to reconstruct his life, but finds that many people he encounters want him dead. However, Bourne realizes that he has the combat and mental skills of a world-class spy—but who does he work for?",
          poster_path: "/aP8swke3gmowbkfZ6lmNidu0y9p.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 18, 9648, 53],
          popularity: 7.8296,
          release_date: "2002-06-14",
          video: false,
          vote_average: 7.467,
          vote_count: 9539,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 55256,
      known_for_department: "Acting",
      name: "Julie Ann Emery",
      original_name: "Julie Ann Emery",
      popularity: 15.8489,
      profile_path: "/A29Nmt41IREXVNMk02cCxN9Ba6i.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/fmDYTtZZQHLBAvvqgdXItqMXBNG.jpg",
          id: 8488,
          title: "Hitch",
          original_title: "Hitch",
          overview:
            "Dating coach Alex 'Hitch' Hitchens mentors a bumbling client, Albert, who hopes to win the heart of the glamorous Allegra Cole. While Albert makes progress, Hitch faces his own romantic setbacks when proven techniques fail to work on Sara Melas, a tabloid reporter digging for dirt on Allegra Cole's love life. When Sara discovers Hitch's connection to Albert – now Allegra's boyfriend – it threatens to destroy both relationships.",
          poster_path: "/x3W9H3nhGQbWSlyI8Amp2F6Z6cz.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [35, 18, 10749],
          popularity: 5.8307,
          release_date: "2005-02-11",
          video: false,
          vote_average: 6.566,
          vote_count: 5930,
        },
        {
          adult: false,
          backdrop_path: "/gYtXT7fJNBRZBbBulO11DoRveLT.jpg",
          id: 400928,
          title: "Gifted",
          original_title: "Gifted",
          overview:
            "Frank, a single man raising his child prodigy niece Mary, is drawn into a custody battle with his mother.",
          poster_path: "/7YB2YrMwIm1g8FyZtlvmVDfRnAT.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [18, 35],
          popularity: 5.9568,
          release_date: "2017-04-07",
          video: false,
          vote_average: 8,
          vote_count: 5678,
        },
        {
          adult: false,
          backdrop_path: "/4nGUe1i0HIAOD3pnVermO9YR5V2.jpg",
          id: 64230,
          name: "Preacher",
          original_name: "Preacher",
          overview:
            "A preacher sets out on a mission to make the almighty himself confess his sin of abandoning the world. With his best friend Cassidy, an alcoholic Irish vampire, his love Tulip, a red blooded gun towing Texan, and the power of genesis, an unholy child born from an angel and a devil, Jesse gives up everything to set the world straight with its creator.",
          poster_path: "/ey1WQajA25E5sFGHSApcqSWUSEc.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [10765, 9648, 18],
          popularity: 79.8392,
          first_air_date: "2016-05-22",
          vote_average: 7.5,
          vote_count: 1202,
          origin_country: ["US"],
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 2641580,
      known_for_department: "Editing",
      name: "Kristin Köster",
      original_name: "Kristin Köster",
      popularity: 15.0972,
      profile_path: null,
      known_for: [
        {
          adult: false,
          backdrop_path: "/iegxEpnbuFZ48c2TReApHWEH6QY.jpg",
          id: 68739,
          name: "Game Two",
          original_name: "Game Two",
          overview:
            "At Game Two, we show our love for video games in a charmingly silly way: The latest game reviews, gaming news, a lot of humor and a good pinch of punch & cardboard - whether for full-blooded gamers, casual gamers or noobs. Game Two is a gaming show, information from the gaming cosmos and comedy. Packed into three entertaining videos per week. Be there when we test games, discuss games news with you and don't take ourselves too seriously again.",
          poster_path: "/tne6Vi2FWIXsX7dIuleZQWd7IUJ.jpg",
          media_type: "tv",
          original_language: "de",
          genre_ids: [99, 35],
          popularity: 27.6804,
          first_air_date: "2016-11-18",
          vote_average: 9,
          vote_count: 2,
          origin_country: ["DE"],
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 64,
      known_for_department: "Acting",
      name: "Gary Oldman",
      original_name: "Gary Oldman",
      popularity: 15.0873,
      profile_path: "/2v9FVVBUrrkW2m3QOcYkuhq9A6o.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/y2DB71C4nyIdMrANijz8mzvQtk6.jpg",
          id: 49026,
          title: "The Dark Knight Rises",
          original_title: "The Dark Knight Rises",
          overview:
            "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
          poster_path: "/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 80, 18, 53],
          popularity: 13.4381,
          release_date: "2012-07-17",
          video: false,
          vote_average: 7.785,
          vote_count: 23310,
        },
        {
          adult: false,
          backdrop_path: "/enNubozHn9pXi0ycTVYUWfpHZm.jpg",
          id: 155,
          title: "The Dark Knight",
          original_title: "The Dark Knight",
          overview:
            "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
          poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [18, 28, 80, 53],
          popularity: 27.8052,
          release_date: "2008-07-16",
          video: false,
          vote_average: 8.521,
          vote_count: 34001,
        },
        {
          adult: false,
          backdrop_path: "/88S6EYQBVyQktDfSqsB33I169jN.jpg",
          id: 6114,
          title: "Bram Stoker's Dracula",
          original_title: "Bram Stoker's Dracula",
          overview:
            "In 19th century England, Count Dracula travels to London and meets Mina Harker, a young woman who appears as the reincarnation of his lost love.",
          poster_path: "/scFDS0U5uYAjcVTyjNc7GmcZw1q.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [10749, 27],
          popularity: 5.9579,
          release_date: "1992-11-13",
          video: false,
          vote_average: 7.448,
          vote_count: 5351,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 17053,
      known_for_department: "Acting",
      name: "Annika Blendl",
      original_name: "Annika Blendl",
      popularity: 15.0773,
      profile_path: "/ifuXml57v4iU7O7fJPcRl3kVd09.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/slXaQ221FgSOsmAOqB7GQpHHjod.jpg",
          id: 9511,
          title: "Rabbit Without Ears 2",
          original_title: "Zweiohrküken",
          overview:
            "Two years have passed. There is a normal life, but handsome Ludo meets his old love, and Anna is very jealous...",
          poster_path: "/vULrURaizz6FNHVmObbPPzFlA3R.jpg",
          media_type: "movie",
          original_language: "de",
          genre_ids: [35, 10749],
          popularity: 0.774,
          release_date: "2009-11-24",
          video: false,
          vote_average: 5.8,
          vote_count: 263,
        },
        {
          adult: false,
          backdrop_path: "/ogg2VK3cp9V8NRKk1Kw4mPebkFm.jpg",
          id: 398826,
          title: "Luna's Revenge",
          original_title: "Luna",
          overview:
            "When Luna’s family is killed in cold blood on a mountain vacation, she barely escapes, and has to discover she’s been living a lie: her dad was a Russian secret agent, and her family was just a front. Luna has the opportunity to flee the country. But first she wants revenge.",
          poster_path: "/kp0pdsw5dA8KXzxun4FrQHM2K0t.jpg",
          media_type: "movie",
          original_language: "de",
          genre_ids: [53, 28],
          popularity: 0.4902,
          release_date: "2018-02-15",
          video: false,
          vote_average: 5.7,
          vote_count: 106,
        },
        {
          adult: false,
          backdrop_path: "/kYeGX6ot8IWO3BrJsnCfFQCo40z.jpg",
          id: 74264,
          title: "The Hunt for the Amber Room",
          original_title: "Die Jagd nach dem Bernsteinzimmer",
          overview:
            "It's the greatest myth of the German post-war era: The Amber Room. Since its disappearance in 1945 from Koenigsberg Castle, legions of treasure hunters have tried and failed to find the room. It is said that Physics genius, Albert Einstein hid the legendary Amber Room from the Nazis in the turmoil of the last days of the war. It bears a secret within its amber - in wrong hands, it could destroy mankind! Our adventurers, Eik, Katharina and Justus, come across an incredible trace and with the help of Einstein's great-granddaughter Mila, together they fight off a ruthless pharmaceutical magnate who spares no effort to get ahold of the Amber Room. From Europe's biggest monument in Leipzig, through the halls of Munich's German Museum, across the dunes of St. Peter-Ording, to the Nazi caves of the Berchtesgaden Alps. The adventurous hunt begins. Written by Dreamtool Entertainment",
          poster_path: "/mJAygUYpDKxEGoR0onsyOgfyijB.jpg",
          media_type: "movie",
          original_language: "de",
          genre_ids: [10770, 12, 28],
          popularity: 0.597,
          release_date: "2012-09-17",
          video: false,
          vote_average: 6.421,
          vote_count: 38,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 500,
      known_for_department: "Acting",
      name: "Tom Cruise",
      original_name: "Tom Cruise",
      popularity: 15.0435,
      profile_path: "/3mShHjSQR7NXOVbdTu5rT2Qd0MN.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/4V1yIoAKPMRQwGBaSses8Bp2nsi.jpg",
          id: 137113,
          title: "Edge of Tomorrow",
          original_title: "Edge of Tomorrow",
          overview:
            "Major Bill Cage is an officer who has never seen a day of combat when he is unceremoniously demoted and dropped into combat. Cage is killed within minutes, managing to take an alpha alien down with him. He awakens back at the beginning of the same day and is forced to fight and die again... and again - as physical contact with the alien has thrown him into a time loop.",
          poster_path: "/nBM9MMa2WCwvMG4IJ3eiGUdbPe6.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 878],
          popularity: 9.5872,
          release_date: "2014-05-27",
          video: false,
          vote_average: 7.631,
          vote_count: 14263,
        },
        {
          adult: false,
          backdrop_path: "/sbkYWB5QcfT00gLUkbNE5LTdhIX.jpg",
          id: 75612,
          title: "Oblivion",
          original_title: "Oblivion",
          overview:
            "Jack Harper is one of the last few drone repairmen stationed on Earth. Part of a massive operation to extract vital resources after decades of war with a terrifying threat known as the Scavs, Jack’s mission is nearly complete. His existence is brought crashing down when he rescues a beautiful  stranger from a downed spacecraft. Her arrival triggers a chain of events that  forces him to question everything he knows and puts the fate of humanity in his hands.",
          poster_path: "/eO3r38fwnhb58M1YgcjQBd3VNcp.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 878, 12, 9648],
          popularity: 6.74,
          release_date: "2013-04-10",
          video: false,
          vote_average: 6.656,
          vote_count: 10943,
        },
        {
          adult: false,
          backdrop_path: "/ih4lZkUpmSE7AP3maymiO72xJ1z.jpg",
          id: 56292,
          title: "Mission: Impossible - Ghost Protocol",
          original_title: "Mission: Impossible - Ghost Protocol",
          overview:
            "Ethan Hunt and his team are racing against time to track down a dangerous terrorist named Hendricks, who has gained access to Russian nuclear launch codes and is planning a strike on the United States. An attempt to stop him ends in an explosion causing severe destruction to the Kremlin and the IMF to be implicated in the bombing, forcing the President to disavow them. No longer being aided by the government, Ethan and his team chase Hendricks around the globe, although they might still be too late to stop a disaster.",
          poster_path: "/eRZTGx7GsiKqPch96k27LK005ZL.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 53, 12],
          popularity: 13.8116,
          release_date: "2011-12-07",
          video: false,
          vote_average: 7.1,
          vote_count: 10223,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 224513,
      known_for_department: "Acting",
      name: "Ana de Armas",
      original_name: "Ana de Armas",
      popularity: 14.44,
      profile_path: "/3vxvsmYLTf4jnr163SUlBIw51ee.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/m7ynwXIvSnhxQPR6pOICrC0L2sO.jpg",
          id: 335984,
          title: "Blade Runner 2049",
          original_title: "Blade Runner 2049",
          overview:
            "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
          poster_path: "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [878, 18],
          popularity: 18.4111,
          release_date: "2017-10-04",
          video: false,
          vote_average: 7.6,
          vote_count: 14208,
        },
        {
          adult: false,
          backdrop_path: "/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg",
          id: 546554,
          title: "Knives Out",
          original_title: "Knives Out",
          overview:
            "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
          poster_path: "/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [35, 80, 9648],
          popularity: 11.8396,
          release_date: "2019-11-27",
          video: false,
          vote_average: 7.842,
          vote_count: 12934,
        },
        {
          adult: false,
          backdrop_path: "/oNoprEND25zXR6Fns8cIZUkuoMc.jpg",
          id: 308266,
          title: "War Dogs",
          original_title: "War Dogs",
          overview:
            "Based on the true story of two young men, David Packouz and Efraim Diveroli, who won a $300 million contract from the Pentagon to arm America's allies in Afghanistan.",
          poster_path: "/mDcPRjZC1bb6LavFU3gwsWdVfCM.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [35, 80, 18],
          popularity: 6.6898,
          release_date: "2016-08-18",
          video: false,
          vote_average: 6.925,
          vote_count: 5108,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 117642,
      known_for_department: "Acting",
      name: "Jason Momoa",
      original_name: "Jason Momoa",
      popularity: 14.3029,
      profile_path: "/3troAR6QbSb6nUFMDu61YCCWLKa.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/qkOw5IZXESOiRH4wzdIYJlBZiCp.jpg",
          id: 297802,
          title: "Aquaman",
          original_title: "Aquaman",
          overview:
            "Half-human, half-Atlantean Arthur Curry is taken on the journey of his lifetime to discover if he is worth of being a king.",
          poster_path: "/ufl63EFcc5XpByEV2Ecdw6WJZAI.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 12, 14],
          popularity: 7.2632,
          release_date: "2018-12-07",
          video: false,
          vote_average: 6.876,
          vote_count: 14367,
        },
        {
          adult: false,
          backdrop_path: "/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
          id: 438631,
          title: "Dune",
          original_title: "Dune",
          overview:
            "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
          poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [878, 12],
          popularity: 24.6477,
          release_date: "2021-09-15",
          video: false,
          vote_average: 7.782,
          vote_count: 13660,
        },
        {
          adult: false,
          backdrop_path: "/7S0bXv3BqCuPfImKRf5kkmBVYZR.jpg",
          id: 572802,
          title: "Aquaman and the Lost Kingdom",
          original_title: "Aquaman and the Lost Kingdom",
          overview:
            "Black Manta seeks revenge on Aquaman for his father's death. Wielding the Black Trident's power, he becomes a formidable foe. To defend Atlantis, Arthur (Aquaman) forges an alliance with his imprisoned brother. They must protect the kingdom.",
          poster_path: "/jcA2QFJ4wuFcG79P97wA7OBLQoL.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 12, 14],
          popularity: 14.1412,
          release_date: "2023-12-20",
          video: false,
          vote_average: 6.606,
          vote_count: 3121,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 573984,
      known_for_department: "Acting",
      name: "Jens Atzorn",
      original_name: "Jens Atzorn",
      popularity: 13.64,
      profile_path: "/4WruGgmRxTSA8WuCoT6vgDuZWJI.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/4J7T7kn6fp4CEds0TxHpN3I6eZW.jpg",
          id: 321620,
          title: "Famous Five 4",
          original_title: "Fünf Freunde 4",
          overview:
            "The famous five George, Julian, Dick, Anne and Timmy the dog are spending holidays together. But when they are invited by Berhard, father of Julian, Dick and Anne, to visit an egyptian exhibition they see a burglar. They have a look at the mummy the burglar was tempering with to find a golden amulet. The famous five decide to visit Egypt to hand over the amulet. When arriving in Egypt Bernhard is arrested because he's asserted he stole the amulet and replaced it with a fake. Now its up to the young detectives to solve the case and prove their fathers innocence.",
          poster_path: "/fx0lziJ5GJDyvOX82Fqyixvn1xp.jpg",
          media_type: "movie",
          original_language: "de",
          genre_ids: [10751, 12, 53, 80],
          popularity: 0.6482,
          release_date: "2015-01-29",
          video: false,
          vote_average: 5.6,
          vote_count: 44,
        },
        {
          adult: false,
          backdrop_path: "/cntonpIL8Ty4K6OsCyWC4Bo6hLe.jpg",
          id: 663100,
          title: "Rosamunde Pilcher: Wo Dein Herz wohnt",
          original_title: "Rosamunde Pilcher: Wo Dein Herz wohnt",
          overview: "",
          poster_path: "/4X7w7qnhsLjPpSMOXABKa5oamCP.jpg",
          media_type: "movie",
          original_language: "de",
          genre_ids: [18],
          popularity: 0.3999,
          release_date: "2018-10-07",
          video: false,
          vote_average: 6.3,
          vote_count: 6,
        },
        {
          adult: false,
          backdrop_path: "/njd9cwOLSvtqohw0xtOSOkCk8mR.jpg",
          id: 324340,
          title: "Summers Downstairs",
          original_title: "Im Sommer wohnt er unten",
          overview:
            "Brothers David and Matthias have contrasting personalities. Long since grown up – one with a wife, the other a girlfriend – they unintentionally meet at their parents' holiday home. Games and plots about power and dominance with unforeseen consequences.",
          poster_path: "/ojfryM4DePAU0UvQa93WKCIdF0a.jpg",
          media_type: "movie",
          original_language: "de",
          genre_ids: [18, 35],
          popularity: 0.1238,
          release_date: "2015-10-29",
          video: false,
          vote_average: 5.9,
          vote_count: 10,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 2005186,
      known_for_department: "Acting",
      name: "Jane Wong",
      original_name: "王貝兒",
      popularity: 13.2849,
      profile_path: "/6UerZ84pnkjeEzMBogxbYti7nQk.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/2T8p4TupZ9RBNy7thUltvAa588q.jpg",
          id: 748412,
          title: "The Calm Beyond",
          original_title: "平靜以後",
          overview:
            "A young woman lives, hidden in plain sight in a ruined Hong Kong building after a tsunami destroyed the city - a castaway on a concrete island. Her concealed existence is changed forever when a small child literally floats into her life.",
          poster_path: "/dLBqqA6oXWzNCPYgYKz9eFIBIeB.jpg",
          media_type: "movie",
          original_language: "cn",
          genre_ids: [878, 53],
          popularity: 1.5472,
          release_date: "2020-10-16",
          video: false,
          vote_average: 7.5,
          vote_count: 75,
        },
        {
          adult: false,
          backdrop_path: "/QlbpTZRlH0eEhjWsNrBWJtfIYI.jpg",
          id: 441531,
          title: "Shock Wave",
          original_title: "拆彈專家",
          overview:
            "When a terrorist who specializes in explosives takes hold of an underground tunnel, he threatens to kill hostages if his demands are not met.",
          poster_path: "/l4G4M6V9UrNRdbcsbnMmEZUyBGw.jpg",
          media_type: "movie",
          original_language: "cn",
          genre_ids: [28, 80, 12, 53],
          popularity: 1.8447,
          release_date: "2017-04-20",
          video: false,
          vote_average: 6.7,
          vote_count: 184,
        },
        {
          adult: false,
          backdrop_path: "/cBlQCu4QQPa7Lz8IXEhMNB10jEg.jpg",
          id: 74639,
          title: "Overheard 2",
          original_title: "竊聽風雲 2",
          overview:
            "Manson Law, a celebrated stockbroker in Hong Kong, is injured in a car accident. The police, led by Inspector Jack Ho, discovers a military surveillance device in the car wreck. Meanwhile, the wiretapper Joe Szema is unveiling his extensive plan that targets the mysterious financial conglomerate, the Landlord Club. The fate of these three men soon intertwines in the cat-and-mouse game that may bring down the entire stock market.",
          poster_path: "/bnQkYQMS1KduqbPNb46JWRtV9Bo.jpg",
          media_type: "movie",
          original_language: "cn",
          genre_ids: [28, 80, 53],
          popularity: 1.1968,
          release_date: "2011-08-18",
          video: false,
          vote_average: 6.5,
          vote_count: 77,
        },
      ],
    },
  ],
  total_pages: 206557,
  total_results: 4131123,
};
